# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :tests do
    run_tests(scheme:"PoliceTests")
  end
  desc "Push a new release build to the App Store"
  lane :release do
    run_tests(scheme:"PoliceTests")
    sync_code_signing(type: "appstore")
    build_app(workspace: "Police.xcworkspace", scheme: "Police")
    upload_to_app_store
  end
end
